{
    parserClass="com.IJVMplugin.parser.IJVMParser"

    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

    psiClassPrefix="IJVM"
    psiImplClassSuffix="Impl"
    psiPackage="com.IJVMplugin.psi"
    psiImplPackage="com.IJVMplugin.psi.impl"

    elementTypeHolderClass="com.IJVMplugin.psi.IJVMTypes"
    elementTypeClass="com.IJVMplugin.psi.IJVMElementType"
    tokenTypeClass="com.IJVMplugin.psi.IJVMTokenType"
}

IJVMFILE ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY VALUE) | KEY | (KEY LETTER SEPARATOR VALUE)